version: '3'
networks:
  db-data-net:
    driver: bridge
services:
  todoapp:
    image: todoapp:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_NAME=app_db
      - DB_USER=app_user
      - DB_PASSWORD=your_secure_password
      - DB_HOST=mysql
      - DB_PORT=3306
    networks:
      db-data-net:
    depends_on:
      - mysql
    restart: unless-stopped
  mysql:
    image: mysql:1.0
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=your_secure_root_password
     - MYSQL_DATABASE=app_db
     - MYSQL_USER=app_user
     - MYSQL_PASSWORD=your_secure_password
    networks:
      - db-data-net
volumes:
  db-data:

